university/config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :sections
  resources :offices
  resources :teachers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

university/app/models/office.rb
class Office < ApplicationRecord
    has_one :teacher, dependent: :nullify
end

university/app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_action :set_office, only: %i[ show edit update destroy ]

  # GET /offices or /offices.json
  def index
    @offices = Office.all
  end

  # GET /offices/1 or /offices/1.json
  def show
  end

  # GET /offices/new
  def new
    @office = Office.new
  end

  # GET /offices/1/edit
  def edit
  end

  # POST /offices or /offices.json
  def create
    @office = Office.new(office_params)

    respond_to do |format|
      if @office.save
        format.html { redirect_to @office, notice: "Office was successfully created." }
        format.json { render :show, status: :created, location: @office }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offices/1 or /offices/1.json
  def update
    respond_to do |format|
      if @office.update(office_params)
        format.html { redirect_to @office, notice: "Office was successfully updated." }
        format.json { render :show, status: :ok, location: @office }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1 or /offices/1.json
  def destroy
    @office.destroy
    respond_to do |format|
      format.html { redirect_to offices_url, notice: "Office was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office
      @office = Office.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def office_params
      params.require(:office).permit(:building_name, :floor_number, :room_number)
    end
end

university/app/helpers/offices_helper.rb
module OfficesHelper
end

university/app/views/offices/_form.html.erb
<%= form_with(model: office) do |form| %>
  <% if office.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(office.errors.count, "error") %> prohibited this office from being saved:</h2>

      <ul>
        <% office.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :building_name %>
    <%= form.text_field :building_name %>
  </div>

  <div class="field">
    <%= form.label :floor_number %>
    <%= form.number_field :floor_number %>
  </div>

  <div class="field">
    <%= form.label :room_number %>
    <%= form.number_field :room_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

university/app/views/offices/edit.html.erb
<h1>Editing Office</h1>

<%= render 'form', office: @office %>

<%= link_to 'Show', @office %> |
<%= link_to 'Back', offices_path %>

university/app/views/offices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Offices</h1>

<table>
  <thead>
    <tr>
      <th>Building name</th>
      <th>Floor number</th>
      <th>Room number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offices.each do |office| %>
      <tr>
        <td><%= office.building_name %></td>
        <td><%= office.floor_number %></td>
        <td><%= office.room_number %></td>
        <td><%= link_to 'Show', office %></td>
        <td><%= link_to 'Edit', edit_office_path(office) %></td>
        <td><%= link_to 'Destroy', office, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Office', new_office_path %>

university/app/views/offices/new.html.erb
<h1>New Office</h1>

<%= render 'form', office: @office %>

<%= link_to 'Back', offices_path %>

university/app/views/offices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Building name:</strong>
  <%= @office.building_name %>
</p>

<p>
  <strong>Floor number:</strong>
  <%= @office.floor_number %>
</p>

<ol>
  <strong>Room number:</strong>
  <%= @office.room_number %>
</ol>

<ol>
  <strong>Teacher:</strong>
  <% if @office.teacher != nil %>
  <%= Teacher.where(office_id: @office.id).first.name if Teacher.find_by(office_id: @office.id) %>
  <% else %>
  <%= "None" %>
  <% end %>
</ol>

<%= link_to 'Edit', edit_office_path(@office) %> |
<%= link_to 'Back', offices_path %>